name: Check PR milestone

on:
  pull_request_target:
    types: [milestoned, demilestoned]
    branches:
      - main

jobs:
  check_milestone:
    if: ${{ github.event.issue.pull_request || github.event.pull_request }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - run: |
      #     echo "${{ toJSON(github.event) }}"

      - name: "Check for milestone on PR"
        uses: actions/github-script@v7
        with:
          script: |
            let milestone = context.payload.pull_request.milestone;

            if(milestone !== null) {
                core.notice(`Milestone is ${milestone.title}`);
            } else {
                core.setFailed("No milestone: Please add a version milestone");
            }
