name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: pip install .
      - run: |
          export TAG_NAME=${{ github.event.inputs.tag }}
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          CI/release.py tag $TAG_NAME --yes

